language: python

dist: trusty

services:
  - postgresql

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
  - pip install -r requirements_test.txt

python:
  - "2.7"

script:
  - pytest contentcuration
