version: '3.4'

x-studio-environment:
  &studio-environment
    MPLBACKEND: ps
    SHELL: /bin/bash
    AWS_S3_ENDPOINT_URL: http://minio:9000
    DATA_DB_HOST: postgres
    DJANGO_SETTINGS_MODULE: contentcuration.dev_settings
    RUN_MODE: docker-compose
    CELERY_TIMEZONE: America/Los_Angeles
    CELERY_REDIS_DB: 0
    CELERY_BROKER_ENDPOINT: redis
    CELERY_RESULT_BACKEND_ENDPOINT: redis
    CELERY_REDIS_PASSWORD: ""
    PROBER_STUDIO_BASE_URL: http://studio-app:8080/{path}

x-studio-worker:
  &studio-worker
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    image: learningequality/studio-app-dev
    depends_on:
      - minio
      - postgres
      - redis
    volumes:
      - .:/src
    environment: *studio-environment
    networks:
      - studio-network

services:
  studio-app:
    <<: *studio-worker
    entrypoint: python docker/entrypoint.py
    command: yarn run devserver
    ports:
      - "8080:8080"
    links:
      - minio
      - postgres

  celery-worker:
    <<: *studio-worker
    command: make prodceleryworkers

  minio:
    image: minio/minio
    entrypoint: minio server /data
    environment:
      MINIO_ACCESS_KEY: development
      MINIO_SECRET_KEY: development
    volumes:
      - minio_data:/data
    networks:
      - studio-network

  postgres:
    image: postgres:9.6
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: learningequality
      POSTGRES_PASSWORD: kolibri
      POSTGRES_DB: kolibri-studio
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    networks:
      - studio-network

  redis:
    image: redis:4.0.9
    networks:
      - studio-network

  cloudprober:
    <<: *studio-worker
    working_dir: /src/deploy
    command: /bin/cloudprober --config_file ./cloudprober.cfg
    # wait until the main app and celery worker have started
    depends_on:
      - studio-app
      - celery-worker
    links:
      - studio-app


volumes:
  minio_data:
  pgdata:

networks:
  studio-network:
