---
# A set of values that are meant to be used for a production setup.
# This includes:
# - an external Postgres, GCS Storage, and external Redis
# - real email sending
# - studio production settings
#
# Note that the secrets will have to be filled up by the caller
# through helm upgrade --set. See REPLACEME placeholders
# for values that need to be set.

settings: contentcuration.sandbox_settings

productionIngress: false

studioApp:
  imageName: "REPLACEME"
  postmarkApiKey: "REPLACEME"
  releaseCommit:
  replicas: 3
  gcs:
    bucketName: develop-studio-content
  pgbouncer:
    replicas: 3
    pool_size: 10
    reserve_pool_size: 10

sentry:
  dsnKey: ""

studioNginx:
  imageName: "REPLACEME"

cloudsql-proxy:
  enabled: true
  cloudsql:
    instances:
      - instance: "develop"
        project: "contentworkshop-159920"
        region: "us-central1"
        port: 5432
  credentials:
    username: ""
    password: ""
    dbname: ""

redis:
  enabled: true


studioProber:
  imageName: "REPLACEME"
  newrelicKey: "REPLACEME"
  newrelicAccountId: "REPLACEME"
  loginProberUsername: "REPLACEME"
  loginProberPassword: "REPLACEME"
  port: 9313
