
# When changing bucket name, make sure to also edit minio.dfeaultBucket.name to reflect
# the same values, or else the bucket won't be created for you
bucketName: develop-studio-content

# The django settings for both studio-app and studio workers
settings: contentcuration.settings


studioApp:
  appPort: 8081
  imageName: gcr.io/github-learningequality-studio/app:nlatest
  replicas: 3
  type: NodePort
  postmarkApiKey:
  ingress:
    enabled: true
  gDrive:
    keyJson:
  pgbouncer:
    replicas: 1
    pool_size: 10
    reserve_pool_size: 5


studioNginx:
  imageName: learningequality/contentworkshop-app-nginx-proxy:v4
  port: 8080


studioWorkers:
  replicas: 1


postgresql:
  internalDBEnabled: true
  postgresUser: learningequality
  postgresDatabase: devDB
  postgresPassword: notsecure
  persistence:
    size: 2Gi
  externalCloudSQL:
    enabled: false
    proxyHostName:

sentry:
  dsnKey:

studioProber:
  imageName: gcr.io/github-learningequality-studio/prober:nlatest
  newrelicKey:
  newrelicAccountId:
  loginProberUsername:
  loginProberPassword:
  port: 9313
