---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "studio.fullname" . }}
  labels:
    app: {{ template "studio.fullname" . }}
    tier: ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
    ingressClassName: "nginx"

spec:
  rules:
    - host: {{.Release.Name}}.studio.cd.learningequality.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ template "studio.fullname" . }}-app
                port:
                  number: 80
