---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "studio.fullname" . }}-django-config
  labels:
    app: {{ template "studio.fullname" . }}
data:
  DJANGO_SETTINGS_MODULE: {{ .Values.settings }}
  DJANGO_LOG_FILE: /var/log/django.log
  MPLBACKEND: PS
  STUDIO_BETA_MODE: "yes"
  RUN_MODE: k8s
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "studio.fullname" . }}-migrate-job
  labels:
    app: {{ template "studio.fullname" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: dbmigrate
        image: {{ .Values.studioApp.imageName }}
        args:
        - make
        - migrate
        envFrom:
        - configMapRef:
            name: {{ template "studio.fullname" . }}-django-config
        env: {{ include "studio.sharedEnvs" . | nindent 8 }}