# Deploy probers only in production environment.
{{- if .Values.productionIngress -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "studio.fullname" . }}-prober
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "studio.fullname" . }}-prober
  template:
    metadata:
      labels:
        app: {{ template "studio.fullname" . }}-prober
    spec:
      containers:
      - name: prober
        image: {{ .Values.studioProber.imageName }}
        ports:
        - containerPort: {{ .Values.studioProber.port }}
        command: ["/deploy/prober-entrypoint.sh"]
        env: {{ include "studio.sharedEnvs" . | nindent 8 }}
        - name: DATA_DB_HOST
          value: {{ template "cloudsql-proxy.fullname" . }}
        - name: PROBER_STUDIO_BASE_URL
          value: http://{{ template "studio.fullname" . }}-app
        - name: CELERY_DASHBOARD_URL
          value: http://{{ template "studio.fullname" . }}-celery-dashboard-service:5555/dashboard
        - name: PROBER_STUDIO_PRODUCTION_MODE_ON
          value: "yes"
        - name: PROBER_STUDIO_USERNAME
          valueFrom:
            secretKeyRef:
              key: login-prober-username
              name: {{ template "studio.fullname" . }}
        - name: PROBER_STUDIO_PASSWORD
          valueFrom:
            secretKeyRef:
              key: login-prober-password
              name: {{ template "studio.fullname" . }}
{{- end }}
