---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "studio.fullname" . }}-prober
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "studio.fullname" . }}-prober
    spec:
      containers:
      - name: prober
        image: {{ .Values.studioProber.imageName }}
        ports:
        - name: prober-webui
          containerPort: {{ .Values.studioProber.port }}
        command:
        - ./deploy/prober-entrypoint.sh
        env: {{ include "studio.sharedEnvs" . | nindent 8 }}
        - name: PROBER_STUDIO_BASE_URL
          value: http://{{ template "studio.fullname" . }}-app.default.svc.cluster.local
