---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "studio.fullname" . }}-prober
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "studio.fullname" . }}-prober
  template:
    metadata:
      labels:
        app: {{ template "studio.fullname" . }}-prober
    spec:
      containers:
      - name: prober
        image: {{ .Values.studioProber.imageName }}
        ports:
        - containerPort: {{ .Values.studioProber.port }}
        command:
        - ./deploy/prober-entrypoint.sh
        env: {{ include "studio.sharedEnvs" . | nindent 8 }}
        - name: PROBER_STUDIO_BASE_URL
          value: http://{{ template "studio.fullname" . }}-app.default.svc.cluster.local
        - name: CELERY_DASHBOARD_URL
          value: http://{{ template "studio.fullname" . }}-celery-dashboard-service.default.svc.cluster.local:5555/dashboard
        - name: PROBER_STUDIO_PRODUCTION_MODE_ON
          value: "yes"
